[package]
org = "ballerinax"
name = "postgresql.cdc.driver"
version = "1.0.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql.cdc.driver"
license = ["Apache-2.0"]
distribution = "2201.12.0"
