[package]
org = "ballerinax"
name = "postgresql.cdc.driver"
version = "1.0.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql.cdc.driver"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[[platform.java21.dependency]]
groupId = "io.debezium"
artifactId = "debezium-connector-postgres"
version = "3.0.8.Final"
path = "./lib/debezium-connector-postgres-3.0.8.Final.jar"
