[package]
org = "ballerinax"
name = "postgresql.cdc.driver"
version = "1.1.0"
authors = ["Ballerina"]
keywords = ["CDC", "Debezium", "PostgreSQL", "Area/Database", "Type/Driver", "Vendor/Red Hat"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql.cdc.driver"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "postgresql.cdc.driver-native"
version = "1.1.0"
path = "../native/build/libs/postgresql.cdc.driver-native-1.1.0.jar"

[[platform.java21.dependency]]
groupId = "io.debezium"
artifactId = "debezium-connector-postgres"
version = "3.5.1.Final"
path = "./lib/debezium-connector-postgres-3.5.1.Final.jar"
